#automatically workflow for github actions to run tests
#name to run test
name: Run Tests 

#When to run the workflow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    #where to run the job
    runs-on: ubuntu-latest
    steps:
      #copy code from repo
      - name: Checkout code
        uses: actions/checkout@v4
      #setup nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      #install dependencies 
      - name: Install dependencies
        run: npm install
      #run tests
      - name: Run tests
        run: npm test
